# -*- coding: utf-8 -*-
"""aula_exercicios_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGWTiAzX8Kfy6RrD31NGgTf5Y-r0bDLh

## Exercício 1: Verifique se um número é positivo, negativo ou zero.
"""

#1. Pergunte o número ao usuário.
#2. Anote o número informado pelo usuário.
#3. Verifique se o número informado é maior, menor ou igual ao número zero.
#4. Se uma das verificações anteriores for verdadeira, considerar as demais falsas
#5. Pegue o resultado verdadeiro da verificação anterior.
#6. Se o número for maior que zero, informar que é um número positivo.
#7. Se o número for igual a zero, informar que é zero.
#8. Se o número for menor que zero, informar que é um número negativo.

num = float(input('Digite um número: '))
if num > 0:
  print('O número é positivo')
elif num < 0:
  print('O número é negativo')
else:
  print('O número é zero')

"""## Exercício 2: Peça dois números e exiba o maior."""

#1. Pergunte ao usuário um número.
#2. Anote esse número.
#3. Pergunte ao usuário um outro número, diferente do primeiro.
#4. Anote também esse número.
#5. Verificar se o primeiro número é maior que o segundo número.
#6. Anotar o maior número dentre os dois.
#7. Exibir o número anotado após a verificação do passo #5.

num1 = float(input('Digite o primeiro número: '))
num2 = float(input('Digite agora o segundo número: '))
if num1 > num2:
  print('O número maior é: ', num1)
elif num1 == num2:
  print('Os números são iguais')
else:
  print('O número maior é: ', num2)

"""## Exercício 3: Verifique se um número é par ou ímpar."""

#1. Pergunte ao usuário um número
#2. Anote o número informado
#3. Efetue a divisão deste número por 2 (dois).
#4. Anote o resultado desta divisão e também o resto.
#5. Verificar se o resultado da divisão é um número inteiro.
#6. Verificar se o resto da divisão é igual a zero.
#7. Em caso de ambas verificações serem verdadeiras, informar que o número é par.
#8. Em caso de uma das verificaçõs ser falsa, informar que o número é ímpar.
#9. Em caso de ambas verificações serem falsas, informar que o número é ímpar.

num = float(input('Digite um número: '))
if num % 2 == 0:
  print('Esse número é par')
else:
  print('Esse número é ímpar')

"""## Exercício 4: Verifique se um ano é bissexto."""

#1. Pergunte ao usuário um ano.
#2. Anote o ano informado pelo usuário.
#3. Verificar se o número informado é múltiplo de 4, mas não é múltiplo de 100.
#4. Verificar se o número informado é múltiplo de 400.
#5. Se as verificações #3 ou #4 forem verdadeiras, informar que o ano é bissexto.
#6. Se as verificações #3 e #4 forem falsas, informar que o ano não é bissexto.

ano = int(input('Informe um ano, com quatro dígitos: '))
if (ano % 4 == 0 and ano % 100 != 0) or ano % 400 == 0:
  print('O ano',ano,'é bissexto')
else:
  print('O ano',ano,'não é bissexto')

"""## Exercício 5: Peça três números e exiba o maior."""

num1 = float(input('Informe o primeiro número: '))
num2 = float(input('Informe o segundo número: '))
num3 = float(input('Informe o terceiro número: '))
print('O maior número é:', max(num1, num2, num3))

"""## Exercício 6: Verifique se um usuário pode votar (idade >= 18)."""

idade = int(input('Informe sua idade, por favor: '))
if idade >= 18:
  print('O usuário já pode votar!')
else:
  print ('O usuário ainda não tem idade para votar!')

"""## Exercício 7: Verifique se já posso ir embora da aula de Análise de Dados sem assinar a folha."""

"""hora = float(input('Informe as horas que pretende sair, seguindo o formato "hora.minuto": '))
if hora >= 21.45:
  print('Você já pode ir embora sem assinar a lista! Bom descanso.')
else:
  print('Você ainda não pode ir embora, espere um pouco mais!')  """

from datetime import datetime, time
print(datetime.now().time())
if datetime.now().time() >= time(hour=00, minute=45):
  print('Pode sair!')
else:
  print('Não pode!')

"""## Exercício 8: Verifique se uma senha digitada corresponde a '1234'."""

senha = input('Informe sua senha: ')
if senha == '1234':
  print('Senha correta!')
else:
  print('Senha incorreta!')

"""## Exercício 9: Verifique se um número está entre 10 e 50."""

num = float(input('Informe um número: '))
if  10 < num < 50:
  print('O número está entre 10 e 50')
else:
  print('O número não está entre 10 e 50')

"""## Exercício 10: Peça ao usuário um número e exiba 'Alto' se for maior que 100 e 'Baixo' se for menor."""

num = float(input('Informe um número: '))
if num > 100:
  print('Alto!')
else:
  print('Baixo!')

"""## Exercício 11: Crie um menu onde o usuário pode escolher entre somar, subtrair, multiplicar e dividir dois números."""

def operacao(op, a, b):
  return{
      '1': a+b,
      '2': a-b,
      '3': a*b,
      '4': a/b if b != 0 else 'Divisão por zero não é aceita'
  }.get(op, 'Operação inválida')

op = input('Escolha: 1 - Soma, 2 - Sub, 3 - Mult, 4 - Div: ')
a, b = map(int, input ('Digite dois números: ').split())
print ('Resultado: ', operacao(op, a, b))

"""## Exercício 12: Crie um menu para converter temperaturas entre Celsius, Fahrenheit e Kelvin."""

def temperaturas(op, t):
  return{
      'Fahrenheit': (t * 1.8)+32,
      'Kelvin': t + 273.15,
  }.get(op, 'Operação inválida')

t = float(input ('Digite a temperatura, em Celsius: '))
op = input('Escolha para qual temperatura converter: Fahrenheit ou Kelvin? ')
print ('Resultado: ', temperaturas(op, t))

"""## Exercício 13: Crie um programa que traduza números de 1 a 5 para palavras (1 = um, 2 = dois...)."""

def numeros(op):
  return{
      '1': 'Um',
      '2': 'Dois',
      '3': 'Três',
      '4': 'Quatro',
      '5': 'Cinco',
  }.get(op, 'Operação inválida')

op = input('Escolha um número para ser escrito por extenso: 1, 2, 3,4 ou 5: ')
print ('Resultado: ', numeros(op))

"""## Exercício 14: Crie um menu onde o usuário pode escolher entre exibir a data, hora ou sair."""

from datetime import datetime, time, date

def calendario(op):
  return{
      'Dia': datetime.now().date(),
      'Hora': datetime.now().time(),
      'Sair': 'Okay, até mais!'
  }.get(op, 'Operação inválida')

op = input('1 - Dia\n2 - Hora\n3 - Sair\n\nEscolha o que exibir: ')
print (calendario(op))

"""## Exercício 15: Implemente um programa que identifica o dia da semana baseado em um número (1 = Segunda, 7 = Domingo)."""

def numeros(op):
  return{
      '1': 'Segunda',
      '2': 'Terça',
      '3': 'Quarta',
      '4': 'Quinta',
      '5': 'Sexta',
      '6': 'Sábado',
      '7': 'Domingo',
  }.get(op, 'Operação inválida')

op = input('Escolha um número: 1, 2, 3, 4, 5, 6 ou 7: ')
print ('Resultado: ', numeros(op))

"""## Exercício 16: Verifique se um número é par ou ímpar usando if ternário."""

num1 = int(input('Informe um número, por favor: '))
print('Par' if num1 % 2 == 0 else 'Ímpar')

"""## Exercício 17: Verifique se um número é positivo ou negativo usando if ternário."""

num1 = int(input('Informe um número, por favor: '))
print('Positivo' if num1 > 0 else 'Negativo')

"""## Exercício 18: Retorne 'Adulto' se a idade for maior ou igual a 18, senão 'Menor de idade'."""

idade = int(input('Informe sua idade: '))
if idade >=18:
  print('Adulto')
else:
  print('Menor de idade')

"""## Exercício 19: Verifique se um número é maior que 100 e retorne 'Grande' ou 'Pequeno'."""

num = float(input('Informe um número, por favor:'))
if num > 100:
  print('Grande!')
else:
  print('Pequeno!')

"""## Exercício 20: Retorne 'Aprovado' se a nota for maior ou igual a 7, senão 'Reprovado'."""

nota = float(input('Informe sua nota, por favor:'))
if nota >=7:
  print('Aprovado!')
else:
  print('Reprovado!')

"""## Exercício 21: Imprima os números de 1 a 10 usando um laço for."""

for i in range (1, 11):
  print (i)

"""## Exercício 22: Imprima os números pares de 1 a 20."""

for i in range (2, 21, 2):
   print (i)

"""## Exercício 23: Calcule a soma dos números de 1 a 100."""

soma = 0
for i in range (1, 101):
  soma = soma+i
print (soma)

"""## Exercício 24: Imprima a tabuada do 5."""

for i in range (5, 51, 5):
  print (i)

"""## Exercício 25: Imprima os 10 primeiros números da sequência de Fibonacci."""

def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)

for i in range(10):
    print(fibonacci(i), end=" ")

"""## Exercício 26: Percorra uma string e imprima cada caractere.

## Exercício 27: Crie um programa que peça um número e imprima sua contagem regressiva até 0.

## Exercício 28: Crie um programa que solicite 5 números ao usuário e exiba a soma deles.

## Exercício 29: Imprima todas as vogais de uma string digitada pelo usuário.

## Exercício 30: Crie um programa que peça 5 números e exiba apenas os números pares.

## Exercício 31: Percorra uma lista de frutas e imprima cada uma.

## Exercício 32: Some todos os números de uma lista.

## Exercício 33: Multiplique cada número de uma lista por 2 e imprima o resultado.

## Exercício 34: Conte quantas palavras existem em uma lista de palavras.

## Exercício 35: Imprima cada letra de uma palavra separadamente.

## Exercício 36: Crie uma lista com 5 números e imprima o maior.

## Exercício 37: Crie uma lista e inverta a ordem dos elementos.

## Exercício 38: Crie uma lista com 5 nomes e remova o último nome.

## Exercício 39: Ordene uma lista de números.

## Exercício 40: Crie uma lista com 5 números e exiba apenas os pares.

## Exercício 41: Crie uma lista e adicione um novo elemento no final.

## Exercício 42: Verifique se um número existe dentro de uma lista.

## Exercício 43: Crie uma lista de números e calcule a média.

## Exercício 44: Crie uma lista de nomes e converta todos para maiúsculas.

## Exercício 45: Crie uma lista de números e remova os duplicados.

## Exercício 46: Crie um dicionário com nomes de alunos e suas notas e exiba a nota de um aluno específico.

## Exercício 47: Adicione um novo aluno e sua nota a um dicionário.

## Exercício 48: Remova um aluno do dicionário.

## Exercício 49: Percorra um dicionário e imprima suas chaves e valores.

## Exercício 50: Verifique se uma chave existe no dicionário.
"""